### ISSUE TITLE
dsf with the cursor outside the function parenthesis

### ISSUE THREAD

**Issue by mawkler** [AndrewRadev/dsf.vim#2] opened 2019-09-26 23:55 UTC
I just started using this plugin and I really love it! However, one thing that I think it's lacking is the ability call `dsf` when the cursor is outside of, i.e. on the name of, the function to be removed. I'm thinking of functionality like in [targets.vim](https://github.com/wellle/targets.vim)'s, which lets you for instance can call `di)` outside a pair of parentheses, and Vim will then jump to the first pair of parentheses and delete the text inside them.

I'll illustrate the desired functionality with an example. Say that we have the following text:
```
baz = bar(foo)
```

And I want to delete the function surrounding `foo` using `dsf` to get this:
```
baz = foo
```
To do this I currently need to have my cursor inside the parentheses. I think it would be neat if I could use `dsf` the same way but with my cursor located for instance at the first character of bar, like this (where `^` is the location of my cursor):
```
baz = bar(foo)
      ^
```

yielding this:
```
baz = foo
```

For the ambiguous case of nested functions, for instance this:
```
baz = bar(foo(foz))
          ^
```

A solution would be to add an alternative mapping, for instance `dsF`, which would then mean the outer function `bar()`, which would yield this:
```
baz = foo(foz)
```
While `dsf` deletes the nested function `foo()`, yielding:
```
baz = bar(foz)
```

Would this be possible to add, or is there a simple Vim script that I can add to my `.vimrc` that would add this functionality?

**Comment by AndrewRadev** [comment] 2019-09-28 09:27
> Would this be possible to add, or is there a simple Vim script that I can add to my .vimrc that would add this functionality?

Well, you could try this:

``` vim
let g:dsf_no_mappings = 1
nmap dsf f(l<Plug>DsfDelete
nmap dsF <Plug>DsfDelete
```

This will make `dsf` go to the next `(`, move right once to get inside, and then execute the core mapping. The `dsF` mapping would apply the core mapping itself.

This is not perfect, because if you're at the innermost layer, `dsf` won't work (not sure why. It seems if `f(` fails, the rest of the mapping stops, which I find somewhat weird). A more complicated bit that seems to work (by separately executing the movement and the deletion) is this:

``` vim
let g:dsf_no_mappings = 1
nmap dsf :exe "normal! f(l"<cr>:exe "normal \<Plug>DsfDelete"<cr>
nmap dsF <Plug>DsfDelete
```

<hr>

That said, as I'm typing this, I'm realizing I might as well at least provide it as a mapping from the plugin, in a backwards-compatible way (with support for repeating with a `.`, and for different kinds of brackets). I've added it as `dsnf`: https://github.com/AndrewRadev/dsf.vim/blob/611f6946a2c69afd6b52362787d710013f1e2e09/doc/dsf.txt#L57-L63

A bit of a clumsy mnemonic, I guess. the `F` idea is nice, but I'd rather not change the built-in, since this variant departs a bit from the "surrounding" idea. And `dn` deletes a search match by default and is likely quite useful. In any case, you should be able to do this:

``` vim
let g:dsf_no_mappings = 1
nmap dsf <Plug>DsfNextDelete
nmap dsF <Plug>DsfDelete
```

**Comment by mawkler** [comment] 2019-10-01 21:30
@AndrewRadev Thanks for adding `DsfNextDelete` I really appreciate that! I do have some additional feedback though.

First of all, I think it would be great if there also was a `DsfNextChange` that (similarly to `DsfDelete` and `DsfChange`) does the same as `DsfDeleteNext`, but preserves the parenthesis and enters insert mode.

Second, and perhaps this is not functionality that you've intended with this plugin, but the behaviour that I intuitively imagined when first using this plugin is the following, where the cursor can be positioned anywhere on `...`, and `└─┘` marks the text that gets deleted:

```
           ..........
baz = bar( foo( baz ) )
           └───┘   └┘     <-- deleted area on dsf
      └───┘          └┘   <-- deleted area on dsF
```

And for the case where the cursor is on or left of the outer function (including parenthesis), `dsf` would look for the next function like this:
```
...........          ..
baz = bar( foo( baz ) )
      └───┘          └┘   <-- deleted area on dsf
```


As I said, this may not be what you intended for this plugin, but I would personally love to get this behaviour in Vim.

**Comment by AndrewRadev** [comment] 2019-10-20 14:34
Sorry for taking a while to get to this.

First off, a lot of what you describe could be achieved with the mappings I described, the only problem (I think, correct me if I'm wrong) is this scenario:

```
               .....
baz = bar( foo( baz ) )
      └───┘          └┘   <-- deleted area on dsF
```

I admit, this doesn't fit my intuition. To me, it seems like this is supposed to delete the *second* surrounding function, but why the second? It feels like a strange behaviour for an atomic mapping. Maybe if I implemented counts to delete the Nth surrounding function like `2dsF`, it might make more sense, although I'm not sure how difficult that would be to get done and what the edge cases would look like.

Is your intuition for this example that `baz` is part of a single expression, `foo(baz)`, which is surrounded by `bar`? If that's the case, what do you think should happen when pressing `dsF` in this scenario?

```
                     .....
baz = quux( bar( foo( baz ) ) )
```

Is the cursor on `baz` part of `foo(baz)` or `bar(foo(baz))`? What should be deleted on `dsF` in this case, do you think? 

Maybe your idea is that the "outer-most" function call should be deleted? That might be tricky to implement, and I'm not sure how reliable or predictable it might be. It might end up being an expression that's nested deeply into some other expression which surprises the user.

**Comment by AndrewRadev** [comment] 2019-10-20 14:39
I've also added `<Plug>DsfNextChange` mapped by default to `csnf` -- let me know if you run into any issues with it.

**Comment by mawkler** [comment] 2019-10-31 16:51
So I intuitively want to be able to do `dsf` when not only inside the function (i.e. the parentheses), but when my cursor is placed anywhere on the function (i.e. on the function's name and on/inside its parentheses). And even better would be if it behaved like [targets.vim](https://github.com/wellle/targets.vim) when the cursor is not on on/inside a function, i.e. looks for the nearest function. If you haven't played around with it I would advice you to do so because it's a great plugin.

In your scenario
```
                     .....
baz = quux( bar( foo( baz ) ) )
```

I could see either functionality make sense, but perhaps it should in that scenario be synonymous with `dsf`, i.e. delete `foo()` and produce

```
baz = quux( bar( baz ) )
```

I would perhaps word it like this: the capital `F` in `dsF` ignores any nested function, and always refers to the function who's parenthesis we are inside (if we're not inside a function it does nothing).

The lowercase `f` would then refer to:
- If the cursor is inside a function *F*'s parentheses:
  - If there's no function inside *F*: the surrounding function *F*
  - If there is a function inside *F*: the closest (to the right) function
- If the cursor is not inside a function's parentheses: the closest (to the right) occurring function on the line.

Does that make sense? The capital `F` functionality isn't crucial, but I think it would give this plugin some extra oomph, because I think the situation with nested functions often occurs and it would be nice to be able to differentiate between nested and surrounding function with one key.

This definition doesn't fully agree with my previous comment, but would look like this:

```
               .....
baz = bar( foo( baz ) )
           └───┘   └┘     <-- deleted area on dsf
           └───┘   └┘     <-- deleted area on dsF
```

```
          .....
baz = bar( foo( baz ) )
           └───┘   └┘     <-- deleted area on dsf
      └───┘          └┘   <-- deleted area on dsF
```

```
..........
baz = bar( foo( baz ) )
      └───┘          └┘   <-- deleted area on dsf
                          <-- deleted area on dsF (nothing)
```

I have no clue how difficult this would be to implement though, and I understand if you think it's too difficult or don't agree with my intuition.

**Comment by AndrewRadev** [comment] 2019-11-24 10:09
Sorry for taking a while to get around to this, been busy.

> I have no clue how difficult this would be to implement though, and I understand if you think it's too difficult or don't agree with my intuition.

To me, the three examples you give make perfect sense, but that's also what the plugin already does, I think -- that's the results I'm getting when I test it out. With the remap I posted before, `dsF = dsf` and `dsf = dsnf`. 

The only difference that I can see is when the cursor is exactly on the `(` of `foo(`, where it doesn't seem to do anything. It's something I need to debug, but is that the thing that's missing right now, or am I misunderstanding something in these definitions?

**Comment by mawkler** [comment] 2019-11-24 21:22
> that's also what the plugin already does

You're right! I think that I made a mistake in my configuration previously. I now get the behavior that I described above with the `dsF = dsf` and `dsf = dsnf` mappings.

And yes, it would be great if the cursor was also included as you mentioned.

**Comment by mawkler** [comment] 2019-11-24 21:54
This is very nitpicky, but I was able to find a small deviation from my suggested definition above (*the capital `F` in `dsF` ignores any nested function, and always refers to the function who's parenthesis we are inside*) by chaining methods. The current behavior looks like this:

```
               .................
baz = bar( foo( far ).faz( boo ) )
                      └───┘   └┘     <-- deleted area on dsf

               ...........
baz = bar( foo( far ).faz( boo ) )
           └───┘   └┘                <-- deleted area on dsF
```

But I would argue that it should rather behave like this:

```
          ...........
baz = bar( foo( far ).faz( boo ) )
           └───┘   └┘                <-- deleted area on dsf

                     ............
baz = bar( foo( far ).faz( boo ) )
                      └───┘   └┘     <-- deleted area on dsf

          .....     ......     ..
baz = bar( foo( far ).faz( boo ) )
      └───┘                     └┘   <-- deleted area on dsF

               .....
baz = bar( foo( far ).faz( boo ) )
           └───┘   └┘                 <-- deleted area on dsF

                          .....
baz = bar( foo( far ).faz( boo ) )
                      └───┘   └┘      <-- deleted area on dsF
```

**Comment by AndrewRadev** [comment] 2019-11-29 20:13
All of the `dsF` examples you give make a lot of sense -- the plugin did not consider nesting at all, and that's useful for getting the right surrounding function. I've pushed some logic to fix this by checking the start and end positions of the surrounding brackets and whether the cursor is within them.

This one is a problem, though:

```
               ..... 
baz = bar( foo( far ).faz( boo ) )
           └───┘   └┘                <-- deleted area on dsf
```

The problem is the "delete next function" logic. It's supposed to jump forward to find a function call, like in this case:

```
surrounding(foo = faz(boo))
```

If the cursor is on `foo`, we *want* it to go forward. This is an issue, because there's no technical way that I can think of to avoid the situation where it jumps *over* a closing bracket to find that function call.

With the surrounding case, the logic is roughly:
- look for a starting function call like `foo(`, backwards from the cursor
- find its closing match
- if the cursor is not inside, go back one symbol and look for a different surrounding (new logic I just pushed)

With the "next closest function case" it's
- look for a starting function call like `foo(`, forwards from the cursor
- find its closing match

At that point, I can't do the "inside" check, because it doesn't make sense -- the cursor should not be inside the brackets, or even inside the "foo" of the function call or the `bar = foo` case won't work with the cursor on `bar`. But now the problem is, what if it's a `bar ) foo` instead? I can't think of a good way to avoid the situation without adding a lot of complexity and probably a lot more edge-case bugs.

<hr>

Logically, it feels to me like this shouldn't be a problem in practice if you *choose* the right mapping for what you want. In this situation:

```
baz = bar( foo( far ).faz( boo ) )
```

If you're in `far` and you want to delete its wrapping `foo`, it makes sense to use `dsF`, because you're trying to delete a surrounding. If you're in `far` and want to delete the `faz`, then it makes sense to use `dsf`, because you're trying to delete the next function call. (I still prefer `dsf` to "delete surrounding" and `dsnf` to "delete surrounding next" :)). The problem comes from trying to have `dsf` *both* delete the next function call *and also* delete the surrounding one. This is what it currently does, but I would honestly even consider removing that second part, so that the two interfaces are clearly distinct.

**Comment by mawkler** [comment] 2019-12-01 23:28
Yeah, I agree that when thinking about it as "delete surrounding next", your argument makes sense :)

The only complaint I have now is the case discussed earlier when the cursor is on a function's `(`, which I personally think should work synomynously to when the cursor is located on the function's name:

```
        this position
              |
              v
          .....
baz = bar( foo( baz ) )
           └───┘   └┘     <-- deleted area on dsf
      └───┘          └┘   <-- deleted area on dsF
```

Currently, `dsf` deletes `bar()` in that case, which doesn't really make sense to me.

What do you think?

**Comment by AndrewRadev** [comment] 2019-12-02 09:22
Yes, I agree, the cursor on brackets doesn't seem to work as it should. I'll see what I can do to fix it.

**Comment by AndrewRadev** [comment] 2019-12-22 13:21
I think I've fixed the issue -- the bracket should be considered part of the function name, so for `outer(inner(foo))` (with the default mappings):

- `dsf` on the inner bracket -- deletes the `outer` function
- `dsnf` on the inner bracket -- deletes the `inner` function

Try it out

**Comment by mawkler** [comment] 2019-12-23 15:51
Seems to be working as expected, great work @AndrewRadev!

**Comment by AndrewRadev** [comment] 2019-12-23 16:20
Awesome, in that case, I'll close the issue for the moment. Feel free to reopen if you run into problems, or open a new one.

**Closed as completed by AndrewRadev** 2019-12-23 16:20 UTC
